name: Download ANGLE Libraries
description: Downloads and validates the ANGLE libraries.

inputs:
  angle_url_base:
    description: Base URL for the ANGLE libraries.
    required: true
  angle_folder:
    description: Directory to download and extract ANGLE libraries.
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up ANGLE Folder
      shell: bash
      run: |
        angle_folder="$(echo "${{ inputs.angle_folder }}" | sed 's|\\|/|g')"
        mkdir -p "$angle_folder"
        echo "ANGLE folder created at: $angle_folder"
    
    - name: Download ANGLE Libraries
      shell: bash
      run: |
        angle_folder="$(echo "${{ inputs.angle_folder }}" | sed 's|\\|/|g')"
        base_url="${{ inputs.angle_url_base }}"

        files=(
          "windows_arm64.zip:$base_url-arm64-windows-release.zip"
          "windows_arm32.zip:$base_url-arm32-windows-release.zip"
          "windows_x86_64.zip:$base_url-x86_64-windows-release.zip"
          "windows_x86_32.zip:$base_url-x86_32-windows-release.zip"
          "macos_arm64.zip:$base_url-arm64-macos-release.zip"
          "macos_x86_64.zip:$base_url-x86_64-macos-release.zip"
          "ios_arm64.zip:$base_url-arm64-ios-release.zip"
          "ios_sim_arm64.zip:$base_url-arm64-ios-sim-release.zip"
          "ios_sim_x86_64.zip:$base_url-x86_64-ios-sim-release.zip"
        )

        pushd "$angle_folder"
        for file in "${files[@]}"; do
          name=${file%%:*}
          url=${file#*:}
          echo "Downloading $name from $url..."
          curl -L -o "$name" "$url"
          if [ $? -ne 0 ]; then
            echo "Error: Failed to download $name." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          unzip -o "$name" && rm -f "$name"
        done
        popd

    - name: Validate ANGLE Libraries
      shell: bash
      run: |
        angle_folder="$(echo "${{ inputs.angle_folder }}" | sed 's|\\|/|g')"
        if [ -z "$(ls -A $angle_folder" ]; then
          echo "Validation failed: ANGLE folder is empty." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        echo "ANGLE libraries downloaded and validated successfully." >> $GITHUB_STEP_SUMMARY
        ls -la $angle_folder >> $GITHUB_STEP_SUMMARY

    - name: Set normalized output
      id: set_normalized_output
      shell: bash
      run: |
        angle_folder="$(echo "${{ inputs.angle_folder }}" | sed 's|\\|/|g')"
        echo "angle_folder=$angle_folder" >> "$GITHUB_OUTPUT"
outputs:
  angle_folder:
    description: Path to the ANGLE libraries folder.
    value: ${{ steps.set_normalized_output.outputs.angle_folder }}
